#!/system/bin/sh
/system/xbin/busybox mkswap /dev/block/zram0
/system/xbin/busybox swapon /dev/block/zram0
echo 134217728 > /sys/block/zram0/disksize
### Pimp my Rom : Ondemand Governor Tweaks 
SAMPLING_RATE1=75000
busybox chmod -R 777 /sys/devices/system/cpu/cpufreq/ondemand
busybox echo 95 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold;
busybox echo 5 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential;
busybox echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy;
busybox echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor;
echo 75000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate;
busybox chmod -R 444 /sys/devices/system/cpu/cpufreq/ondemand
### Pimp my Rom : Interactive Governor Tweaks 
busybox chmod -R 777 /sys/devices/system/cpu/cpufreq/interactive
busybox echo 95 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
busybox echo 1000000 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
busybox echo 10000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
busybox echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/timer_rate
busybox chmod -R 777 /sys/devices/system/cpu/cpufreq/interactive
### Pimp my Rom : Conservative Governor Tweaks 
SAMPLING_RATE3=75000
busybox chmod -R 777 /sys/devices/system/cpu/cpufreq/conservative
busybox echo 95 > /sys/devices/system/cpu/cpufreq/conservative/up_threshold;
busybox echo 35 > /sys/devices/system/cpu/cpufreq/conservative/down_threshold;
busybox echo 10 > /sys/devices/system/cpu/cpufreq/conservative/freq_step;
echo 75000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate;
busybox echo 1 > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor;
busybox chmod -R 444 /sys/devices/system/cpu/cpufreq/conservative
### Pimp my Rom : Disable I/O Stats 
if [ -e /queue/iostats ]; then
busybox echo 0 > /queue/iostats;
fi;  
### Pimp my Rom : Default I/O Scheduler Tweaks
if [ -e /queue/rotational ]; then
echo 0 > /queue/rotational; fi;
if [ -e /queue/nr_requests ]; then
echo 1024 > /queue/nr_requests; fi;
### Pimp my Rom : Re-Enable Vsync
mount -o remount,rw /sys /sys
busybox mount -t debugfs debugfs /sys/kernel/debug
busybox echo '1' > /sys/kernel/debug/msm_fb/0/vsync_enable
umount /sys/kernel/debug
### Pimp my Rom : Disable Normalized Sleeper
echo NO_NORMALIZED_SLEEPER > /sys/kernel/debug/sched_features;
### Pimp my Rom : Disable Gentle Fair Sleeper
echo NO_GENTLE_FAIR_SLEEPERS > /sys/kernel/debug/sched_features;

### Pimp my Rom : Disable New Fair Sleeper
echo NO_NEW_FAIR_SLEEPERS > /sys/kernel/debug/sched_features;
### Pimp my Rom : Force GPU Rendering on 2d Operations (init.d part)
cp -pf /system/lib/egl/libGLES_android.so /sdcard/Android/data/com.androguide.pimpmyrom/files/libGLES_android.so
rm -f /system/lib/egl/libGLES_android.so
busybox sed -i '/0 0 android/d' /system/lib/egl/egl.cfg
### Pimp my Rom : Ext4 File-Systems optimization & instant-mount
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /cache
### Pimp my Rom : External SD I/O Tweaks
busybox echo 128 > /sys/devices/virtual/bdi/7:0/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:1/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:2/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:3/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:4/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:5/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:6/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:7/read_ahead_kb
busybox echo 4096 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
busybox echo 4096 > /sys/devices/virtual/bdi/default/read_ahead_kb
busybox echo 97 > /sys/devices/virtual/bdi/179:0/max_ratio
busybox echo 97 > /sys/devices/virtual/bdi/default/max_ratio
busybox echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
### Pimp my Rom : Battery Savings
busybox echo 500 > /proc/sys/vm/dirty_expire_centisecs
busybox echo 1000 > /proc/sys/vm/dirty_writeback_centisecs
