#!/system/bin/sh
### Pimp my Rom : 128mb zRam Compression
#echo 134217728 > /sys/block/zram0/disksize
#/system/xbin/busybox mkswap /dev/block/zram0
#/system/xbin/busybox swapon /dev/block/zram0

mount -o remount,rw /system
echo "300000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "300000" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo "300000" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo "300000" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
echo "1036000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "1036000" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo "1036000" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo "1036000" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
#rm -rf sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
cat /etc/init.d/vdd_levels > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "400000000" > /sys/class/kgsl/kgsl-3do/gpuclk
echo "100" > /proc/sys/vm/swappiness
### Pimp my Rom : Battery Savings
echo "500" > /proc/sys/vm/dirty_expire_centisecs
echo "1000" > /proc/sys/vm/dirty_writeback_centisecs
mount -o remount,ro /system
#swapon /data/swapfile
