#!/system/bin/sh
### Pimp my Rom : Disable I/O Stats 
### Pimp my Rom : Disable I/O Stats 
### Pimp my Rom : Default I/O Scheduler Tweaks
if [ -e /queue/rotational ]; then
echo 0 > /queue/rotational; fi;
### Pimp my Rom : Disable I/O Stats 
### Pimp my Rom : Default I/O Scheduler Tweaks
if [ -e /queue/rotational ]; then
echo 0 > /queue/rotational; fi;
### Pimp my Rom : Disable New Fair Sleeper
### Pimp my Rom : Disable I/O Stats 
### Pimp my Rom : Default I/O Scheduler Tweaks
if [ -e /queue/rotational ]; then
echo 0 > /queue/rotational; fi;
### Pimp my Rom : Disable New Fair Sleeper
### Pimp My Rom : Entropy Generator
entropy-gen
### Pimp my Rom : 128mb zRam Compression
/system/xbin/busybox mkswap /dev/block/zram0
/system/xbin/busybox swapon /dev/block/zram0
echo 134217728 > /sys/block/zram0/disksize
### Pimp my Rom : Disable I/O Stats 
if [ -e /queue/iostats ]; then
busybox echo 0 > /queue/iostats;
fi;  
### Pimp my Rom : Default I/O Scheduler Tweaks
if [ -e /queue/rotational ]; then
echo 0 > /queue/rotational; fi;
if [ -e /queue/nr_requests ]; then
echo 1024 > /queue/nr_requests; fi;
### Pimp my Rom : Re-Enable Vsync
mount -o remount,rw /sys /sys
busybox mount -t debugfs debugfs /sys/kernel/debug
busybox echo '1' > /sys/kernel/debug/msm_fb/0/vsync_enable
umount /sys/kernel/debug
### Pimp my Rom : Disable Normalized Sleeper
echo NO_NORMALIZED_SLEEPER > /sys/kernel/debug/sched_features;
### Pimp my Rom : Disable Gentle Fair Sleeper
echo NO_GENTLE_FAIR_SLEEPERS > /sys/kernel/debug/sched_features;

### Pimp my Rom : Disable New Fair Sleeper
echo NO_NEW_FAIR_SLEEPERS > /sys/kernel/debug/sched_features;
### Pimp my Rom : Ext4 File-Systems optimization & instant-mount
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /cache
### Pimp my Rom : External SD I/O Tweaks
busybox echo 8 > /sys/block/mtdblock0/bdi/read_ahead_kb
busybox echo 8 > /sys/block/mtdblock1/bdi/read_ahead_kb
busybox echo 8 > /sys/block/mtdblock2/bdi/read_ahead_kb
busybox echo 8 > /sys/block/mtdblock3/bdi/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:0/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:1/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:2/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:3/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:4/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:5/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:6/read_ahead_kb
busybox echo 128 > /sys/devices/virtual/bdi/7:7/read_ahead_kb
busybox echo 4096 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
busybox echo 4096 > /sys/devices/virtual/bdi/default/read_ahead_kb
busybox echo 97 > /sys/devices/virtual/bdi/179:0/max_ratio
busybox echo 97 > /sys/devices/virtual/bdi/default/max_ratio
busybox echo 4096 > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
### Pimp my Rom : Battery Savings
busybox echo 500 > /proc/sys/vm/dirty_expire_centisecs
busybox echo 1000 > /proc/sys/vm/dirty_writeback_centisecs
